create or replace TABLE PIZZASUMMARY.PIZZASUMMARY.PIZZA_SALES (
	PIZZA_ID NUMBER(38,0),
	ORDER_ID NUMBER(38,0),
	PIZZA_NAME_ID VARCHAR(128),
	QUANTITY NUMBER(38,0),
	ORDER_DATE VARCHAR(128),
	ORDER_TIME VARCHAR(128),
	UNIT_PRICE NUMBER(38,2),
	TOTAL_PRICE NUMBER(38,2),
	PIZZA_SIZE VARCHAR(128),
	PIZZA_CATEGORY VARCHAR(128),
	PIZZA_INGREDIENTS VARCHAR(128),
	PIZZA_NAME VARCHAR(128)
);
